### ISSUE TITLE
Retornar os eventos de um pacote a partir do seu Tracking Code

### ISSUE THREAD

**Issue by alexandregama** [alexandregama/correios-tracking-java-sdk#2]
# Objetivo

Retornar os eventos de um pacote a partir do seu Tracking Code. Esta issue é extremamente básica e somente irá cobrir a forma mais simples de retornar a lista de eventos de um pacote.

# To Do

- [x] Retornar a lista de eventos de um pacote a partir do seu Tracking Code
- [x] Converter os objetos dos correios em objetos próprios para o Tracking
- [x] Converter os eventos dos correios em objetos próprios para o Tracking
- [x] Converter o destino enviado pelos correios em objetos próprios para o Tracking
- [x] Permitir que o usuário passe as credenciais necessárias para o uso da API

# Observações

- Não fazer o tratamento do campo **tipo** enviado para os correios via API
- Não fazer o tratamento do campo **resultado** enviado para os correios via API
- Não fazer o tratamento do campo **lingua** enviado para os correios via API
- Não fazer o tratamento do campo **objetos** enviado para os correios via API
